version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/sh0e1/gotree
    environment:
      GO111MODULE: "on"

    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-cache-{{ checksum "/go/src/github.com/sh0e1/gotree/go.sum" }}
      - run:
          name: Run unit tests
          command: |
            make lint
            make test
      - save_cache:
          key: go-mod-cache-{{ checksum "/go/src/github.com/sh0e1/gotree/go.sum" }}
          paths:
            - "/go/pkg/mod/cache"
